[package]
name = "udx-native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# async-std = "1.11.0"
# async-io = "1.6.0"
bitflags = "1.3.2"
tokio = { version = "1.17.0", features = ["net", "macros"] }
